package orchestra

import (
	"fmt"
	"strings"
	"time"

	"github.com/MochaCosine1206/orchestra/internal/orchestrator"
)

// GeneratePRDescription produces GitHub-flavored Markdown from a GoResult.
// Uses collapsible <details> sections for verbose data.
func GeneratePRDescription(result *orchestrator.GoResult) string {
	var b strings.Builder

	// Summary
	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("- **Session:** `%s`\n", result.SessionID))
	b.WriteString(fmt.Sprintf("- **Duration:** %s\n", result.Duration.Round(time.Second)))
	b.WriteString(fmt.Sprintf("- **Tasks:** %d total, %d done, %d failed\n",
		result.TaskCount, result.DoneCount, result.FailedCount))
	if result.StagingBranch != "" {
		b.WriteString(fmt.Sprintf("- **Branch:** `%s`\n", result.StagingBranch))
	}
	b.WriteString("\n")

	// Changes
	if result.MergeResult != nil {
		mr := result.MergeResult
		b.WriteString("## Changes\n\n")

		if len(mr.Merged) > 0 {
			b.WriteString("<details>\n")
			b.WriteString(fmt.Sprintf("<summary>Merged branches (%d)</summary>\n\n", len(mr.Merged)))
			for _, br := range mr.Merged {
				b.WriteString(fmt.Sprintf("- `%s`\n", br))
			}
			b.WriteString("\n</details>\n\n")
		}

		if len(mr.Failed) > 0 {
			b.WriteString("<details>\n")
			b.WriteString(fmt.Sprintf("<summary>Failed branches (%d)</summary>\n\n", len(mr.Failed)))
			for _, br := range mr.Failed {
				b.WriteString(fmt.Sprintf("- `%s`\n", br))
			}
			b.WriteString("\n</details>\n\n")
		}

		if len(mr.Skipped) > 0 {
			b.WriteString(fmt.Sprintf("**Skipped:** %d branches\n\n", len(mr.Skipped)))
		}

		if len(mr.AutoResolved) > 0 {
			b.WriteString(fmt.Sprintf("**Auto-resolved conflicts:** %d branches\n\n", len(mr.AutoResolved)))
		}
	}

	// Test Results
	b.WriteString("## Test Results\n\n")
	if result.MergeResult != nil && result.MergeResult.TestsFailed {
		b.WriteString("- Status: **FAILED**\n")
	} else {
		b.WriteString("- Status: **PASSED**\n")
	}
	b.WriteString("\n")

	// Agent Stats
	b.WriteString("## Agent Stats\n\n")
	b.WriteString("| Metric | Value |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Tasks | %d |\n", result.TaskCount))
	b.WriteString(fmt.Sprintf("| Done | %d |\n", result.DoneCount))
	b.WriteString(fmt.Sprintf("| Failed | %d |\n", result.FailedCount))
	if result.RefiningCount > 0 {
		b.WriteString(fmt.Sprintf("| Refining | %d |\n", result.RefiningCount))
	}
	if result.AbandonedCount > 0 {
		b.WriteString(fmt.Sprintf("| Abandoned | %d |\n", result.AbandonedCount))
	}
	b.WriteString(fmt.Sprintf("| Duration | %s |\n", result.Duration.Round(time.Second)))

	if result.ReconcileResult != nil {
		rr := result.ReconcileResult
		if rr.GoalAlignmentScore > 0 {
			b.WriteString(fmt.Sprintf("| Alignment | %.0f%% |\n", rr.GoalAlignmentScore*100))
		}
	}

	b.WriteString("\n---\n*Generated by Claude Orchestra*\n")

	return b.String()
}

// GeneratePRTitle returns a concise PR title under 70 characters derived from GoResult data.
func GeneratePRTitle(result *orchestrator.GoResult) string {
	title := fmt.Sprintf("[Orchestra] %d/%d tasks done", result.DoneCount, result.TaskCount)
	if result.FailedCount > 0 {
		title += fmt.Sprintf(" (%d failed)", result.FailedCount)
	}
	if len(title) > 70 {
		title = title[:67] + "..."
	}
	return title
}
