#!/usr/bin/env bash
#
# scaffold-homebrew-tap.sh — Create the MochaCosine1206/homebrew-tap repo
#
# Idempotent: checks for prerequisites and existing repo before acting.
# Requires: gh CLI (authenticated), git
#
set -euo pipefail

ORG="MochaCosine1206"
REPO="homebrew-tap"
FULL_REPO="${ORG}/${REPO}"

# ── Prerequisites ────────────────────────────────────────────────────────────

if ! command -v gh &>/dev/null; then
  echo "ERROR: gh CLI not found. Install it: https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo "ERROR: gh CLI not authenticated. Run: gh auth login" >&2
  exit 1
fi

# ── Create repo if it doesn't exist ─────────────────────────────────────────

if gh repo view "$FULL_REPO" &>/dev/null; then
  echo "Repo ${FULL_REPO} already exists — skipping creation."
else
  echo "Creating repo ${FULL_REPO}..."
  gh repo create "$FULL_REPO" \
    --public \
    --description "Homebrew tap for Plyne Technologies tools (orchestra, etc.)" \
    --clone=false
  echo "Repo created."
fi

# ── Clone into a temp directory for scaffolding ─────────────────────────────

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "Cloning ${FULL_REPO} into temp directory..."
gh repo clone "$FULL_REPO" "$TMPDIR/repo" -- --depth=1

cd "$TMPDIR/repo"

# ── Formula directory ────────────────────────────────────────────────────────

if [ -d "Formula" ]; then
  echo "Formula/ directory already exists — skipping."
else
  mkdir -p Formula
  cat > Formula/.gitkeep <<'GITKEEP'
# Formulae are auto-generated by GoReleaser on tag push.
# See the orchestra repo's .goreleaser.yaml for details.
GITKEEP
  echo "Created Formula/ directory."
fi

# ── Tap README ───────────────────────────────────────────────────────────────

if [ -f "README.md" ] && grep -q "homebrew-tap" README.md 2>/dev/null; then
  echo "README.md already exists — skipping."
else
  cat > README.md <<'README'
# Plyne Technologies Homebrew Tap

Official [Homebrew](https://brew.sh) tap for tools by Plyne Technologies.

## Usage

```bash
brew tap mochacosine1206/tap
brew install orchestra
```

## Available Formulae

| Formula | Description |
|---------|-------------|
| `orchestra` | Multi-agent orchestration system for Claude Code |

## Updating

```bash
brew update
brew upgrade orchestra
```

## Troubleshooting

If you run into issues:

```bash
brew doctor
brew untap mochacosine1206/tap && brew tap mochacosine1206/tap
brew install orchestra
```

## How It Works

Formulae in this tap are automatically updated by [GoReleaser](https://goreleaser.com/)
whenever a new version tag is pushed to the
[orchestra](https://github.com/MochaCosine1206/orchestra) repository.
README
  echo "Created README.md."
fi

# ── CI workflow: brew audit ──────────────────────────────────────────────────

WORKFLOW_DIR=".github/workflows"
WORKFLOW_FILE="${WORKFLOW_DIR}/audit.yml"

if [ -f "$WORKFLOW_FILE" ]; then
  echo "audit.yml workflow already exists — skipping."
else
  mkdir -p "$WORKFLOW_DIR"
  cat > "$WORKFLOW_FILE" <<'WORKFLOW'
name: Homebrew Audit

on:
  push:
    paths:
      - "Formula/**"
  pull_request:
    paths:
      - "Formula/**"

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Audit formulae
        run: |
          for formula in Formula/*.rb; do
            [ -f "$formula" ] || continue
            echo "==> Auditing $formula"
            brew audit --strict "$formula"
          done

      - name: Test formulae
        run: |
          for formula in Formula/*.rb; do
            [ -f "$formula" ] || continue
            echo "==> Testing $formula"
            brew install --build-from-source "$formula"
            brew test "$formula" || true
          done
WORKFLOW
  echo "Created ${WORKFLOW_FILE}."
fi

# ── Commit and push scaffolding ──────────────────────────────────────────────

if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "No changes to commit — tap is already fully scaffolded."
else
  git add -A
  git commit -m "chore: scaffold Homebrew tap (Formula/, README, CI audit workflow)"
  git push origin HEAD
  echo "Scaffolding committed and pushed."
fi

echo ""
echo "Done! Tap is ready at: https://github.com/${FULL_REPO}"
echo "Next: configure GoReleaser in the orchestra repo to publish formulae here."
