// Package main implements a mock agent process that simulates claude -p
// without making API calls. Used for stress testing Orchestra.
//
// Usage:
//
//	mock-agent -p "task prompt" [flags]
//	  --duration <seconds>   How long to "work" (default: 10)
//	  --exit-code <code>     Exit code (default: 0)
//	  --fail-after <secs>    Succeed for N seconds then crash (0 = never)
//	  --files <count>        Number of files to create/modify (default: 1)
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

func main() {
	prompt := flag.String("p", "", "Task prompt (ignored, for CLI compatibility)")
	duration := flag.Int("duration", 10, "How long to work in seconds")
	exitCode := flag.Int("exit-code", 0, "Exit code")
	failAfter := flag.Int("fail-after", 0, "Succeed for N seconds then crash (0 = never)")
	fileCount := flag.Int("files", 1, "Number of files to create/modify")

	// Accept and ignore claude flags for CLI compatibility.
	flag.String("output-format", "stream-json", "")
	flag.String("model", "opus", "")
	flag.String("permission-mode", "bypassPermissions", "")
	flag.Bool("verbose", false, "")

	flag.Parse()

	_ = prompt // prompt is accepted but not used

	// Emit stream-json init event.
	emitEvent("system", map[string]any{
		"type":       "init",
		"session_id": fmt.Sprintf("mock-%d", time.Now().UnixNano()),
		"model":      "mock-agent",
	})

	start := time.Now()
	tickInterval := time.Duration(*duration) * time.Second / 5
	if tickInterval < time.Second {
		tickInterval = time.Second
	}

	ticker := time.NewTicker(tickInterval)
	defer ticker.Stop()

	// Create files to simulate agent work.
	createFiles(*fileCount)

	// Simulate work with periodic heartbeat events.
	for {
		select {
		case <-ticker.C:
			elapsed := time.Since(start)

			// Check fail-after.
			if *failAfter > 0 && int(elapsed.Seconds()) >= *failAfter {
				emitEvent("assistant", map[string]any{
					"type": "text",
					"text": "Error: context window exhausted",
				})
				os.Exit(1)
			}

			// Emit tool use event (heartbeat).
			emitEvent("assistant", map[string]any{
				"type": "tool_use",
				"name": "Read",
				"input": map[string]any{
					"file_path": "mock-file.go",
				},
			})

			// Check if duration elapsed.
			if int(elapsed.Seconds()) >= *duration {
				emitResult(*exitCode)
				os.Exit(*exitCode)
			}
		}
	}
}

func createFiles(count int) {
	cwd, err := os.Getwd()
	if err != nil {
		return
	}
	for i := 0; i < count; i++ {
		name := fmt.Sprintf("mock-output-%d.go", i)
		path := filepath.Join(cwd, name)
		content := fmt.Sprintf("package mock\n\n// Generated by mock-agent at %s\nfunc MockFunc%d() {}\n", time.Now().Format(time.RFC3339), i)
		_ = os.WriteFile(path, []byte(content), 0644)
	}
}

func emitEvent(role string, content map[string]any) {
	event := map[string]any{
		"type": role,
		"message": map[string]any{
			"role":    role,
			"content": []any{content},
		},
		"timestamp": time.Now().Format(time.RFC3339Nano),
	}
	data, _ := json.Marshal(event)
	fmt.Fprintln(os.Stdout, string(data))
}

func emitResult(exitCode int) {
	result := map[string]any{
		"type":       "result",
		"session_id": fmt.Sprintf("mock-%d", time.Now().UnixNano()),
		"cost_usd":   0.0,
		"is_error":   exitCode != 0,
		"duration_ms": 10000,
		"num_turns":   5,
	}
	data, _ := json.Marshal(result)
	fmt.Fprintln(os.Stdout, string(data))
}
